// ============================================================
//  CAREER KNOWLEDGE BASE
//  All career data used by the webhook handlers
// ============================================================

const careerData = {
  ai_ml: {
    name: "AI / Machine Learning",
    overview:
      "AI/ML is one of the fastest-growing tech domains. It involves building intelligent systems that can learn from data, make predictions, and automate complex decisions. Applications span healthcare, finance, autonomous vehicles, NLP, computer vision, and more.",
    skills: {
      technical: ["Python", "NumPy / Pandas", "Scikit-Learn", "TensorFlow / PyTorch", "SQL", "Statistics & Probability", "Linear Algebra", "Data Visualization (Matplotlib, Seaborn)", "MLOps (MLflow, Kubeflow)", "Cloud ML (AWS SageMaker / GCP Vertex AI)"],
      soft: ["Analytical Thinking", "Problem Solving", "Research Mindset", "Communication of Results", "Attention to Detail"],
    },
    roadmap: {
      beginner: ["1. Learn Python (2–3 months)", "2. Study Statistics & Linear Algebra (1 month)", "3. Pandas, NumPy for data manipulation (1 month)", "4. Scikit-Learn for classical ML algorithms (2 months)", "5. Build 2 ML projects (regression + classification)", "6. Learn basics of Deep Learning (TensorFlow/Keras)", "7. Deploy a model on Streamlit / HuggingFace Spaces"],
      intermediate: ["1. Deep dive into Deep Learning (CNNs, RNNs, Transformers)", "2. Study Natural Language Processing (NLP)", "3. Learn MLOps — model tracking, CI/CD for ML", "4. Work on Kaggle competitions", "5. Study Computer Vision with OpenCV + PyTorch", "6. Build end-to-end ML pipeline projects"],
      advanced: ["1. Study LLM fine-tuning and RAG systems", "2. Contribute to open-source ML repos (HuggingFace)", "3. Learn distributed training (multi-GPU)", "4. MLOps at scale (Kubernetes + KubeFlow)", "5. Research paper implementation & publication", "6. Architect enterprise ML systems"],
    },
    projects: ["🔹 House Price Prediction (Regression)", "🔹 Sentiment Analysis on Twitter Data (NLP)", "🔹 Image Classifier using CNN (Computer Vision)", "🔹 Chatbot using Rasa or fine-tuned GPT", "🔹 Stock Price Forecasting with LSTM"],
    jobRoles: ["ML Engineer", "Data Scientist", "AI Research Scientist", "NLP Engineer", "Computer Vision Engineer", "MLOps Engineer", "AI Product Manager", "Deep Learning Engineer"],
    salary: {
      india: "₹6 LPA (Fresher) → ₹25 LPA (Mid) → ₹50+ LPA (Senior/Lead)",
      global: "$85K (Junior) → $140K (Mid) → $200K+ (Senior/Principal)",
    },
    demand: "🔥 Extremely High. Every industry is adopting AI. India alone will need 1 million AI professionals by 2026. Global demand growing at 40% YoY.",
    workPressure: "🔴 High — Requires continuous learning, research reading, and experiment cycles. Deadlines around model performance are intense.",
    aiRisk: { level: "🟢 Low", reason: "AI actually creates more AI jobs. ML Engineers build AI — they don't get replaced by it. However, basic data labeling roles face automation." },
    growth: "ML Intern → Junior ML Engineer → ML Engineer → Senior ML Engineer → ML Lead / Architect → AI Director / VP of AI",
    certifications: ["Google Professional ML Engineer", "AWS Certified ML Specialty", "Deep Learning Specialization (Coursera – Andrew Ng)", "TensorFlow Developer Certificate", "IBM AI Engineering (Coursera)"],
    topCompanies: ["Google DeepMind", "OpenAI", "Microsoft AI", "Amazon AWS AI", "Flipkart AI", "Walmart Labs", "Zomato AI", "TCS AI CoE", "Infosys Nia"],
    freeResources: ["fast.ai (free deep learning course)", "Andrew Ng's ML Course (Coursera – audit free)", "HuggingFace Course", "Kaggle Learn", "YouTube: Sentdex, 3Blue1Brown"],
    paidCourses: ["Deep Learning Specialization – Coursera (₹3,000)", "ML Bootcamp – Udemy (₹499)", "Zero to Mastery ML – ZTM Academy"],
    tools: ["Jupyter Notebook", "VS Code", "Google Colab", "MLflow", "Docker", "AWS SageMaker", "HuggingFace", "Weights & Biases"],
    freelancing: "🟡 Medium. Kaggle competitions, Upwork ML projects, AI consulting. Requires a strong portfolio.",
    abroad: "🟢 Excellent. US, Canada, UK, Germany, Netherlands have massive demand. H1B, Canada PR, EU Blue Card accessible.",
    indiaMarket: "Bengaluru, Hyderabad, Pune, and Chennai are top AI hubs. Product companies (Google, Microsoft, Amazon India) pay top ₹. Startups offer ESOPs.",
    dailyWork: "Review model metrics, experiment with new architectures, write code for training pipelines, collaborate with data engineers, present findings to product teams.",
    interviewTips: ["Study ML algorithms from scratch (implement them)", "Practice Leetcode (Medium level) for coding rounds", "Be ready to explain bias-variance tradeoff, regularization, gradient descent", "Build a strong GitHub with ML projects", "Know SQL and basic statistics deeply"],
    resumeTips: ["Highlight Kaggle rank / competition medals", "Show end-to-end project links (GitHub + deployed demo)", "Quantify impact: 'Improved model accuracy by 15%'", "Include certifications prominently", "List frameworks and cloud tools in skills section"],
    collegeDegree: "Not strictly required. However, top companies (Google, Meta) prefer a degree in CS/Math/Statistics. Many successful ML engineers are self-taught with strong portfolios.",
  },

  data_science: {
    name: "Data Science",
    overview: "Data Science combines statistics, programming, and domain expertise to extract insights from data. It drives business decisions across industries — from e-commerce recommendations to healthcare diagnostics.",
    skills: {
      technical: ["Python / R", "SQL", "Pandas, NumPy", "Data Visualization (Tableau, Power BI, Matplotlib)", "Statistical Analysis", "Machine Learning (Scikit-Learn)", "Excel", "Spark (Big Data)", "Cloud Platforms (AWS/GCP/Azure)"],
      soft: ["Storytelling with Data", "Business Acumen", "Critical Thinking", "Communication", "Curiosity"],
    },
    roadmap: {
      beginner: ["1. Python basics + Pandas (2 months)", "2. SQL for data querying (1 month)", "3. Statistics fundamentals (1 month)", "4. Data visualization with Matplotlib & Seaborn (3 weeks)", "5. Intro to ML with Scikit-Learn (2 months)", "6. Build your first EDA project on Kaggle"],
      intermediate: ["1. Advanced SQL (window functions, CTEs)", "2. Power BI or Tableau for dashboards", "3. Feature engineering & model tuning", "4. A/B Testing and hypothesis testing", "5. Build a data pipeline project"],
      advanced: ["1. Big Data with Apache Spark", "2. Data architecture and data warehouse design", "3. MLOps and production deployment", "4. Business strategy + stakeholder management", "5. Real-time analytics"],
    },
    projects: ["🔹 Sales Dashboard in Power BI / Tableau", "🔹 Customer Churn Prediction (Classification)", "🔹 COVID-19 Data EDA and Visualization", "🔹 Recommendation System (Collaborative Filtering)"],
    jobRoles: ["Data Scientist", "Data Analyst", "Business Intelligence Analyst", "Data Engineer", "Analytics Manager", "Research Analyst"],
    salary: { india: "₹5 LPA (Fresher) → ₹18 LPA (Mid) → ₹40+ LPA (Senior)", global: "$75K (Junior) → $120K (Mid) → $170K+ (Senior)" },
    demand: "🔥 Very High. Data is the new oil. Every company needs data scientists to make sense of their data.",
    workPressure: "🟡 Medium — Deadline-driven but mostly 9–6 work culture in corporate roles. Startups can be more demanding.",
    aiRisk: { level: "🟡 Medium", reason: "Basic data analyst roles face some automation (AutoML, automated dashboards). But strategic and interpretive roles remain human-driven." },
    growth: "Data Analyst → Data Scientist → Senior Data Scientist → Lead Data Scientist → Head of Data / Chief Data Officer",
    certifications: ["Google Data Analytics (Coursera)", "IBM Data Science Professional (Coursera)", "Microsoft Power BI Data Analyst", "Tableau Desktop Specialist", "AWS Data Analytics Specialty"],
    topCompanies: ["Amazon", "Flipkart", "Myntra", "Zomato", "McKinsey Analytics", "BCG Gamma", "Mu Sigma", "Fractal Analytics"],
    freeResources: ["Kaggle Learn (free datasets + tutorials)", "StatQuest (YouTube)", "Google Data Analytics – Coursera (audit)", "Mode Analytics SQL Tutorial"],
    paidCourses: ["Jose Portilla Data Science – Udemy", "IBM Data Science Specialization – Coursera"],
    tools: ["Jupyter Notebook", "Tableau", "Power BI", "SQL Workbench", "Google BigQuery", "Apache Spark"],
    freelancing: "🟢 Good. Dashboards, business reports, analytics consulting are all in demand on Upwork and Toptal.",
    abroad: "🟢 Strong demand in US, UK, Canada, Australia, Singapore.",
    indiaMarket: "Mumbai, Bengaluru, Gurgaon, Pune. BFSI, e-commerce, and consulting sectors are biggest hirers.",
    dailyWork: "Query databases, clean and analyze data, build dashboards, present findings to stakeholders, collaborate with business teams.",
    interviewTips: ["Know SQL deeply (JOINs, window functions, subqueries)", "Practice statistics concepts (CLT, hypothesis testing)", "Prepare case studies on business metrics", "Have at least 2 end-to-end projects on GitHub"],
    resumeTips: ["Show Tableau/Power BI dashboard screenshots", "Quantify: 'Reduced churn by 10% through ML model'", "Include SQL + Python proficiency clearly"],
    collegeDegree: "A degree in Statistics, Math, CS, or Economics helps. But many data scientists switch from other fields with certifications.",
  },

  web_development: {
    name: "Web Development",
    overview: "Web development involves building and maintaining websites and web applications. It's split into Frontend (UI), Backend (server/database logic), and Full Stack (both). It's the most accessible tech career with massive freelancing potential.",
    skills: {
      technical: ["HTML, CSS, JavaScript", "React.js / Vue.js / Angular (Frontend)", "Node.js / Python (Django/Flask) / PHP (Backend)", "REST APIs & GraphQL", "Databases: MySQL, PostgreSQL, MongoDB", "Git & GitHub", "TypeScript", "Docker basics", "AWS / Firebase deployment"],
      soft: ["Design Sense (UI/UX basics)", "Problem Solving", "Communication", "Attention to Detail", "Time Management"],
    },
    roadmap: {
      beginner: ["1. HTML + CSS fundamentals (4 weeks)", "2. JavaScript basics (6 weeks)", "3. Build 3 static websites", "4. Learn React.js (8 weeks)", "5. Learn Node.js + Express + REST API (6 weeks)", "6. Connect to a database (MongoDB or PostgreSQL)", "7. Deploy to Vercel / Render"],
      intermediate: ["1. TypeScript", "2. State management (Redux / Zustand)", "3. Authentication (JWT, OAuth)", "4. Docker basics", "5. Cloud deployment (AWS / GCP)", "6. Testing (Jest, Cypress)"],
      advanced: ["1. Microservices architecture", "2. WebSockets & real-time apps", "3. Performance optimization", "4. System design for scalable web apps", "5. Lead a team / open-source contribution"],
    },
    projects: ["🔹 Portfolio Website with React", "🔹 E-commerce app (React + Node + MongoDB)", "🔹 Real-time Chat App (Socket.io)", "🔹 Blog Platform with CMS"],
    jobRoles: ["Frontend Developer", "Backend Developer", "Full Stack Developer", "React Developer", "Node.js Developer", "MERN Stack Developer", "PHP Developer", "WordPress Developer"],
    salary: { india: "₹3.5 LPA (Fresher) → ₹15 LPA (Mid) → ₹35+ LPA (Senior)", global: "$60K (Junior) → $110K (Mid) → $160K+ (Senior)" },
    demand: "🔥 Very High. Every business needs a website. Huge freelancing market globally.",
    workPressure: "🟡 Medium — Project-based work can have tight deadlines, but mostly manageable. Freelancers set their own pace.",
    aiRisk: { level: "🟡 Medium", reason: "AI tools like GitHub Copilot and Webflow automate basic tasks. However, complex full-stack engineering and system design remain human-driven." },
    growth: "Junior Dev → Developer → Senior Dev → Tech Lead → Engineering Manager → CTO",
    certifications: ["Meta Front-End Developer (Coursera)", "freeCodeCamp Certifications (Free)", "AWS Developer Associate", "MongoDB Developer Certification"],
    topCompanies: ["TCS, Infosys, Wipro (India)", "Razorpay, Zepto, Swiggy (Startups)", "Google, Meta, Netflix (Global)", "Remote-first: GitLab, Shopify, Basecamp"],
    freeResources: ["freeCodeCamp.org", "The Odin Project", "MDN Web Docs", "YouTube: Traversy Media, Fireship, Codevolution"],
    paidCourses: ["The Web Developer Bootcamp – Colt Steele (Udemy)", "Full Stack Open – Helsinki University (Free but comprehensive)"],
    tools: ["VS Code", "Chrome DevTools", "Postman", "Figma", "Git/GitHub", "Vercel", "Docker"],
    freelancing: "🟢 Excellent. Web development is the #1 freelancing skill. High demand on Upwork, Fiverr, Toptal.",
    abroad: "🟢 Strong. Remote-first companies worldwide hire web devs. US, UK, Canada, Germany, Netherlands.",
    indiaMarket: "Huge demand everywhere. Bengaluru, Pune, Hyderabad, Delhi NCR. Product companies pay ₹20–40 LPA for senior devs.",
    dailyWork: "Write code, attend standup meetings, code reviews, fix bugs, collaborate with designers, deploy features.",
    interviewTips: ["Master JavaScript deeply (closures, event loop, promises)", "Know React hooks well", "Practice 50+ DSA problems (Arrays, Strings, Trees)", "Build 3 impressive projects with live URLs"],
    resumeTips: ["Always include live demo links + GitHub", "Mention specific frameworks and versions", "Show measurable impact: 'Reduced load time by 40%'"],
    collegeDegree: "Not required. Portfolio speaks louder than a degree in web dev. Many top devs are self-taught.",
  },

  cybersecurity: {
    name: "Cybersecurity",
    overview: "Cybersecurity protects systems, networks, and data from digital attacks. It includes ethical hacking, network security, application security, and incident response. One of the highest-demand fields globally due to rising cyber threats.",
    skills: {
      technical: ["Networking (TCP/IP, DNS, HTTP)", "Linux proficiency", "Python / Bash scripting", "Penetration Testing (Metasploit, Burp Suite)", "SIEM tools (Splunk, IBM QRadar)", "Cryptography", "Vulnerability Assessment (Nessus, OpenVAS)", "Cloud Security (AWS/GCP)", "OWASP Top 10", "Incident Response"],
      soft: ["Ethical Mindset", "Attention to Detail", "Analytical Thinking", "Confidentiality", "Continuous Learning"],
    },
    roadmap: {
      beginner: ["1. Networking fundamentals: CompTIA Network+ material (6 weeks)", "2. Linux basics (4 weeks)", "3. CompTIA Security+ (3 months)", "4. Try Hack Me beginner path (2 months)", "5. Python scripting for security (1 month)", "6. Practice on TryHackMe / Hack The Box"],
      intermediate: ["1. Certified Ethical Hacker (CEH) or eJPT", "2. Web App Pentesting (Burp Suite + OWASP)", "3. Network penetration testing", "4. SIEM and SOC analyst skills", "5. Active Directory attacks and defenses"],
      advanced: ["1. OSCP Certification (offensive security)", "2. Malware analysis & reverse engineering", "3. Red Team vs Blue Team exercises", "4. Cloud security architecture", "5. Bug bounty programs (HackerOne, Bugcrowd)"],
    },
    projects: ["🔹 Build a home lab with VMs and practice CTF", "🔹 Web vulnerability scanner in Python", "🔹 Network packet analyzer", "🔹 Capture The Flag (CTF) writeups on GitHub"],
    jobRoles: ["Security Analyst", "Ethical Hacker / Penetration Tester", "SOC Analyst", "Security Engineer", "Cloud Security Architect", "CISO (Chief Information Security Officer)", "Malware Analyst", "Bug Bounty Hunter"],
    salary: { india: "₹4 LPA (Fresher) → ₹20 LPA (Mid) → ₹50+ LPA (Senior/CISO)", global: "$75K (Junior) → $130K (Mid) → $200K+ (Senior)" },
    demand: "🔥 Critical. Cybercrime costs will hit $10.5 trillion annually by 2025. Every org needs security professionals.",
    workPressure: "🔴 High — Incident response can be 24/7. On-call duties. High-stakes decisions under pressure.",
    aiRisk: { level: "🟢 Low", reason: "AI creates new attack vectors that humans must defend against. AI tools assist security analysts but can't replace human judgment in complex threats." },
    growth: "SOC Analyst → Security Engineer → Senior Security Engineer → Security Architect → CISO",
    certifications: ["CompTIA Security+", "CEH (Certified Ethical Hacker)", "OSCP (most respected)", "CISSP (senior level)", "AWS Security Specialty", "eJPT (beginner friendly)"],
    topCompanies: ["Palo Alto Networks", "CrowdStrike", "Wipro CyberSecurity", "HCL Security", "Deloitte", "KPMG", "Tata Communications", "Quick Heal"],
    freeResources: ["TryHackMe (free tier)", "Hack The Box", "YouTube: Professor Messer, IppSec", "OWASP.org", "Cybrary"],
    paidCourses: ["TCM Security Courses (affordable)", "Offensive Security (OSCP)", "SANS Institute (enterprise)"],
    tools: ["Kali Linux", "Burp Suite", "Metasploit", "Nmap", "Wireshark", "Nessus", "Splunk"],
    freelancing: "🟡 Moderate. Bug bounty is the best form. Consulting for small businesses also available.",
    abroad: "🟢 Excellent. US, UK, Australia, UAE, Singapore — all high demand. Security clearance jobs pay extremely well.",
    indiaMarket: "Demand growing rapidly. BFSI, government, defense, and IT services are top hirers. Bengaluru, Delhi NCR, Hyderabad.",
    dailyWork: "Monitor security alerts, analyze logs, investigate incidents, conduct vulnerability scans, write security reports, update threat models.",
    interviewTips: ["Know OWASP Top 10 thoroughly", "Be able to explain common attack types (SQLi, XSS, CSRF)", "Show CTF participation on LinkedIn/GitHub", "Know networking fundamentals deeply"],
    resumeTips: ["List certifications prominently", "Show CTF achievements and rankings", "Mention specific tools: Burp Suite, Metasploit, Splunk", "Link to write-ups on GitHub or Medium"],
    collegeDegree: "Certifications often matter more than degrees in cybersecurity. CEH, OSCP, CISSP are industry gold standards.",
  },

  cloud_computing: {
    name: "Cloud Computing",
    overview: "Cloud Computing involves delivering computing services (servers, storage, databases, networking, analytics) over the internet. AWS, Azure, and GCP are the big three. Massive demand as enterprises migrate to cloud.",
    skills: {
      technical: ["AWS / Azure / GCP fundamentals", "Linux & Bash", "Networking (VPC, DNS, Load Balancing)", "Infrastructure as Code (Terraform, CloudFormation)", "Containers (Docker, Kubernetes)", "CI/CD pipelines", "Cloud security", "Serverless (Lambda, Cloud Functions)", "Monitoring (CloudWatch, Prometheus)"],
      soft: ["Problem Solving", "Documentation", "Cost Optimization Mindset", "Communication", "Adaptability"],
    },
    roadmap: {
      beginner: ["1. Linux & Networking fundamentals (1 month)", "2. AWS Cloud Practitioner (2 months)", "3. AWS Solutions Architect Associate (3 months)", "4. Learn Docker (1 month)", "5. Deploy first app on AWS EC2 / S3"],
      intermediate: ["1. Kubernetes (CKA certification)", "2. Terraform for IaC", "3. Multi-cloud architecture", "4. CI/CD with GitHub Actions + AWS CodePipeline", "5. Cloud cost optimization strategies"],
      advanced: ["1. AWS Solutions Architect Professional", "2. Cloud security architecture", "3. Multi-region HA systems design", "4. FinOps (cloud cost management)", "5. Architect enterprise-grade cloud solutions"],
    },
    projects: ["🔹 Deploy a 3-tier web app on AWS (EC2 + RDS + S3)", "🔹 Set up Kubernetes cluster with monitoring", "🔹 Infrastructure as Code with Terraform", "🔹 Serverless API with AWS Lambda + API Gateway"],
    jobRoles: ["Cloud Engineer", "Cloud Architect", "DevOps Engineer", "Cloud Security Engineer", "Solutions Architect", "Cloud Consultant", "SRE (Site Reliability Engineer)"],
    salary: { india: "₹6 LPA (Fresher) → ₹25 LPA (Mid) → ₹60+ LPA (Architect)", global: "$90K (Junior) → $145K (Mid) → $220K+ (Architect)" },
    demand: "🔥 Very High. Cloud migration is happening across all industries. AWS alone has 32% market share.",
    workPressure: "🟡 Medium to High — On-call rotation for production incidents. Complex multi-cloud architectures can be stressful.",
    aiRisk: { level: "🟢 Low", reason: "AI uses cloud infrastructure — it expands demand. Cloud architects design the systems AI runs on." },
    growth: "Cloud Support → Cloud Engineer → Senior Cloud Engineer → Cloud Architect → Principal Architect / Cloud Director",
    certifications: ["AWS Cloud Practitioner (starter)", "AWS Solutions Architect Associate ⭐", "Google Associate Cloud Engineer", "Azure Administrator (AZ-104)", "Kubernetes CKA", "Terraform Associate"],
    topCompanies: ["Amazon AWS", "Microsoft Azure", "Google Cloud", "Infosys Cloud", "TCS Cloud", "Accenture Cloud", "Capgemini"],
    freeResources: ["AWS Free Tier + official docs", "Google Cloud Skills Boost (free labs)", "KodeKloud (free tier)", "YouTube: TechWorld with Nana"],
    paidCourses: ["Stephane Maarek AWS courses (Udemy ⭐)", "A Cloud Guru / PluralSight", "KodeKloud Pro"],
    tools: ["AWS Console", "Terraform", "Kubernetes", "Docker", "Ansible", "Prometheus + Grafana", "Jenkins"],
    freelancing: "🟡 Moderate. Cloud consulting for SMBs. AWS architecture reviews. Migration projects.",
    abroad: "🟢 Excellent. One of the highest-paying skills globally. Easy visa sponsorship.",
    indiaMarket: "Massive demand. All major IT companies hiring cloud professionals. Bengaluru, Hyderabad, Pune top hubs.",
    dailyWork: "Manage cloud infrastructure, handle incidents, write IaC code, optimize costs, collaborate with development teams.",
    interviewTips: ["Know AWS core services deeply (EC2, S3, VPC, IAM, RDS, Lambda)", "Study well-architected framework principles", "Practice cloud architecture design questions", "Have hands-on lab experience"],
    resumeTips: ["List all cloud certifications with dates", "Show cloud projects with architecture diagrams", "Mention cost savings achieved: 'Reduced cloud spend by 30%'"],
    collegeDegree: "Certifications dominate. AWS SAA is widely recognized. Degree helpful but not required.",
  },

  devops: {
    name: "DevOps",
    overview: "DevOps bridges development and operations by automating software delivery, infrastructure management, and monitoring. It emphasizes collaboration, CI/CD pipelines, and reliability engineering.",
    skills: {
      technical: ["Linux & Shell Scripting", "Git & GitHub", "CI/CD (Jenkins, GitHub Actions, GitLab CI)", "Docker & Kubernetes", "Terraform / Ansible", "Cloud (AWS/Azure/GCP)", "Monitoring (Prometheus, Grafana, ELK Stack)", "Python / Bash scripting", "Nginx / Apache"],
      soft: ["Collaboration", "Automation Mindset", "Reliability Focus", "Communication", "Incident Management"],
    },
    roadmap: {
      beginner: ["1. Linux basics + shell scripting (1 month)", "2. Git/GitHub mastery (2 weeks)", "3. Docker fundamentals (1 month)", "4. Learn CI/CD with GitHub Actions (1 month)", "5. Cloud basics (AWS/Azure) (2 months)", "6. Basic Kubernetes (1 month)"],
      intermediate: ["1. Advanced Kubernetes (Helm, Operators)", "2. Terraform for IaC", "3. Ansible for configuration management", "4. Advanced monitoring setup", "5. Security in DevOps (DevSecOps)"],
      advanced: ["1. SRE practices (SLO, SLI, error budgets)", "2. Platform engineering", "3. GitOps (ArgoCD, Flux)", "4. Large-scale Kubernetes cluster management", "5. Chaos engineering"],
    },
    projects: ["🔹 CI/CD pipeline for a Node.js app (GitHub Actions + Docker + AWS)", "🔹 Kubernetes cluster with auto-scaling", "🔹 Full monitoring stack with Prometheus + Grafana", "🔹 Infrastructure provisioning with Terraform"],
    jobRoles: ["DevOps Engineer", "Site Reliability Engineer (SRE)", "Platform Engineer", "Cloud DevOps Engineer", "Build & Release Engineer", "Infrastructure Engineer"],
    salary: { india: "₹6 LPA (Fresher) → ₹22 LPA (Mid) → ₹55+ LPA (Senior)", global: "$85K (Junior) → $140K (Mid) → $200K+ (SRE/Lead)" },
    demand: "🔥 Very High. Every tech company needs DevOps. SRE at Google/Netflix is one of the most coveted roles.",
    workPressure: "🔴 High — Production incidents can happen at 3 AM. On-call rotations are common.",
    aiRisk: { level: "🟢 Low", reason: "AI assists with automation but can't replace the human judgment needed for complex system failures and architecture decisions." },
    growth: "DevOps Engineer → Senior DevOps → DevOps Lead → Platform Engineer → Director of Engineering",
    certifications: ["CKA (Certified Kubernetes Administrator) ⭐", "AWS DevOps Engineer Professional", "HashiCorp Terraform Associate", "GitLab CI/CD Specialist", "Docker Certified Associate"],
    topCompanies: ["Atlassian", "HashiCorp", "Netflix", "Spotify", "Amazon", "Flipkart", "Razorpay", "CRED"],
    freeResources: ["KodeKloud (free tier)", "Play with Docker / Play with Kubernetes", "YouTube: TechWorld with Nana ⭐", "Kubernetes official docs"],
    paidCourses: ["Mumshad Mannambeth CKA Course (KodeKloud)", "DevOps Bootcamp – Udemy"],
    tools: ["Jenkins", "GitHub Actions", "Docker", "Kubernetes", "Terraform", "Ansible", "Prometheus", "Grafana", "ArgoCD"],
    freelancing: "🟡 Moderate. Infrastructure automation consulting for startups. AWS setup projects.",
    abroad: "🟢 Excellent demand in US, UK, Germany, Netherlands. Remote DevOps roles widely available.",
    indiaMarket: "Demand surging with startup boom. Bengaluru, Hyderabad, Pune top locations. SRE roles at Indian unicorns pay ₹40–60 LPA.",
    dailyWork: "Deploy code releases, manage infrastructure, respond to incidents, automate pipelines, collaborate with dev and security teams.",
    interviewTips: ["Know Linux commands and troubleshooting thoroughly", "Explain CI/CD pipeline design for a given scenario", "Study Kubernetes architecture deeply", "Be ready for 'how would you debug a failing pod' questions"],
    resumeTips: ["List specific tools with experience level", "Show pipeline projects with diagrams", "Mention MTTR improvements: 'Reduced deployment time by 70%'"],
    collegeDegree: "Not required. Certifications like CKA carry significant weight. Hands-on experience beats degree.",
  },

  ui_ux: {
    name: "UI/UX Design",
    overview: "UI/UX Design focuses on creating intuitive, beautiful user experiences. UI deals with visual design; UX focuses on usability, research, and user journey. Growing in importance as digital products proliferate.",
    skills: {
      technical: ["Figma ⭐", "Adobe XD", "Sketch", "Wireframing & Prototyping", "User Research Methods", "Usability Testing", "Design Systems", "HTML/CSS basics (for dev handoff)", "Information Architecture", "Accessibility (WCAG)"],
      soft: ["Empathy", "Creativity", "Communication", "Attention to Detail", "User Advocacy", "Storytelling"],
    },
    roadmap: {
      beginner: ["1. Fundamentals: Color theory, Typography, Spacing (2 weeks)", "2. Learn Figma from scratch (4 weeks)", "3. Study UX principles: Norman's Design of Everyday Things", "4. Conduct 3 usability tests", "5. Build 2 app redesign projects", "6. Create Behance/Dribbble portfolio"],
      intermediate: ["1. Design Systems (Material Design, HIG, custom)", "2. Advanced Figma (components, auto-layout, variants)", "3. User research methods (interviews, surveys, card sorting)", "4. Motion design basics (Principle, After Effects)", "5. Work on real client projects or hackathons"],
      advanced: ["1. Strategic UX (OKRs, business alignment)", "2. Leading design teams", "3. Design thinking facilitation", "4. Advanced research (diary studies, eye tracking)", "5. Product strategy"],
    },
    projects: ["🔹 Redesign a popular app (Zomato, Uber, etc.)", "🔹 Design a mobile banking app from scratch", "🔹 Build a full design system in Figma", "🔹 UX case study with user research + testing"],
    jobRoles: ["UI Designer", "UX Designer", "Product Designer", "UX Researcher", "Interaction Designer", "Visual Designer", "Design Lead", "Chief Design Officer"],
    salary: { india: "₹3.5 LPA (Fresher) → ₹15 LPA (Mid) → ₹35+ LPA (Senior/Lead)", global: "$65K (Junior) → $110K (Mid) → $170K+ (Senior)" },
    demand: "🔥 High. Every digital product needs a designer. UX Research roles are especially scarce.",
    workPressure: "🟢 Low to Medium — Creative work, mostly healthy work culture. Deadline pressure during product launches.",
    aiRisk: { level: "🟡 Medium", reason: "AI tools like Midjourney and Galileo AI assist with visual generation. But UX research, empathy-driven design, and strategy remain human-led." },
    growth: "Junior Designer → Designer → Senior Designer → Lead Designer → Design Manager → VP of Design / CDO",
    certifications: ["Google UX Design Certificate (Coursera)", "Interaction Design Foundation Courses", "Nielsen Norman UX Certification", "Figma UI Design Certification"],
    topCompanies: ["Swiggy", "Flipkart", "Razorpay", "CRED", "Google", "Apple", "Airbnb", "Design agencies (ThoughtWorks, Publicis Sapient)"],
    freeResources: ["Figma Community (free resources)", "Laws of UX (lawsofux.com)", "YouTube: DesignCourse, AJ&Smart", "NNGroup Articles"],
    paidCourses: ["Google UX Design – Coursera (₹2500/month)", "Interaction Design Foundation (affordable monthly)"],
    tools: ["Figma ⭐", "Adobe XD", "Miro", "Maze (usability testing)", "Hotjar", "Notion", "Zeplin"],
    freelancing: "🟢 Good. UI design for websites/apps is highly in demand on Fiverr and Upwork.",
    abroad: "🟡 Good. US, UK, Netherlands, Germany. Remote design roles common at product companies.",
    indiaMarket: "Growing fast with startup ecosystem. Bengaluru, Mumbai, Pune. Product designers at unicorns earn ₹25–40 LPA.",
    dailyWork: "User research, creating wireframes, building prototypes in Figma, presenting to stakeholders, iterating based on feedback.",
    interviewTips: ["Walk through your case studies confidently", "Explain your design decisions with user research backing", "Know design principles (Gestalt, Hick's Law, Fitts' Law)", "Show 3–5 detailed case studies in portfolio"],
    resumeTips: ["Portfolio is everything — use Behance, Dribbble, or personal site", "Show before/after redesigns with metrics", "List research methods used (user interviews, A/B tests)"],
    collegeDegree: "Portfolio matters far more than degree. Many top designers are self-taught. Bootcamps like Springboard work well.",
  },

  mobile_dev: {
    name: "Mobile Development",
    overview: "Mobile development involves building iOS and Android applications. You can specialize natively (Swift for iOS, Kotlin for Android) or use cross-platform frameworks like Flutter and React Native.",
    skills: {
      technical: ["Dart + Flutter OR React Native", "Swift (iOS) OR Kotlin (Android)", "REST APIs integration", "Firebase", "State Management (Provider, Bloc, Redux)", "App Store / Play Store submission", "SQLite / Hive (local storage)", "Push Notifications", "CI/CD for mobile"],
      soft: ["User-centric Thinking", "Attention to Performance", "Collaboration with Designers", "Problem Solving"],
    },
    roadmap: {
      beginner: ["1. Learn Dart basics (2 weeks)", "2. Flutter fundamentals (6 weeks)", "3. Build 3 simple apps (counter, todo, weather)", "4. REST API integration in Flutter (1 month)", "5. Firebase integration (auth, Firestore)", "6. Publish first app to Play Store"],
      intermediate: ["1. State management (Riverpod / Bloc)", "2. Advanced animations in Flutter", "3. Native platform integration", "4. Unit and widget testing", "5. CI/CD with Codemagic / GitHub Actions"],
      advanced: ["1. Flutter Web + Desktop", "2. Performance optimization", "3. Custom native plugins", "4. App architecture (Clean Architecture)", "5. Lead mobile team"],
    },
    projects: ["🔹 Task Manager App (Flutter + Firebase)", "🔹 E-commerce Mobile App", "🔹 Real-time Chat App (Flutter + Firebase)", "🔹 Expense Tracker with charts"],
    jobRoles: ["Flutter Developer", "Android Developer", "iOS Developer", "React Native Developer", "Mobile App Developer", "Mobile Tech Lead"],
    salary: { india: "₹4 LPA (Fresher) → ₹16 LPA (Mid) → ₹38+ LPA (Senior)", global: "$70K (Junior) → $120K (Mid) → $170K+ (Senior)" },
    demand: "🔥 High. India has 750M+ smartphone users. Mobile-first economy drives huge demand.",
    workPressure: "🟡 Medium — Sprint-based work, app store review timelines can be stressful.",
    aiRisk: { level: "🟡 Medium", reason: "AI assists with code generation but complex app architecture, UX optimization, and platform-specific nuances remain human-driven." },
    growth: "Junior Mobile Dev → Mobile Dev → Senior Mobile Dev → Mobile Tech Lead → Head of Mobile Engineering",
    certifications: ["Google Associate Android Developer", "Flutter Certified Developer", "Meta iOS Developer (Coursera)", "Udacity Android Nanodegree"],
    topCompanies: ["Swiggy", "Zepto", "PhonePe", "Meesho", "Google", "Meta", "Zomato", "MakeMyTrip"],
    freeResources: ["Flutter official docs + YouTube channel", "Google Codelabs", "YouTube: Rivaan Ranawat, FilledStacks"],
    paidCourses: ["Angela Yu Flutter Course – Udemy ⭐", "London App Brewery Flutter Bootcamp"],
    tools: ["Flutter SDK", "Android Studio", "Xcode", "Firebase", "Postman", "Codemagic"],
    freelancing: "🟢 Good. High demand for app development on Fiverr and Upwork. Startup MVPs are lucrative.",
    abroad: "🟡 Good. Strong demand in US, UK, UAE, Australia for Flutter/React Native developers.",
    indiaMarket: "Huge demand with India's fintech, edtech, and e-commerce boom. Bengaluru, Hyderabad, Pune.",
    dailyWork: "Build app features, integrate APIs, fix bugs, test on real devices, work with designers, submit app updates.",
    interviewTips: ["Know Flutter widget tree and lifecycle deeply", "Understand state management patterns", "Be ready for DSA coding rounds", "Show published apps on Play Store / App Store"],
    resumeTips: ["Link live Play Store / App Store apps", "Show GitHub with Flutter/Android projects", "Mention download counts if available"],
    collegeDegree: "Not required. Published apps are the best proof of skill.",
  },

  blockchain: {
    name: "Blockchain / Web3",
    overview: "Blockchain is the technology behind cryptocurrencies, NFTs, and decentralized applications (dApps). Web3 refers to the decentralized internet built on blockchain. It's a niche but high-paying field.",
    skills: {
      technical: ["Solidity (Smart Contracts)", "Ethereum fundamentals", "Web3.js / Ethers.js", "Hardhat / Truffle (dev frameworks)", "IPFS (decentralized storage)", "DeFi protocols", "React.js (for dApp frontends)", "NFT standards (ERC-721, ERC-1155)", "Layer 2 solutions (Polygon, Arbitrum)", "Security auditing"],
      soft: ["Analytical Mindset", "Self-learning", "Community Engagement", "Risk Assessment"],
    },
    roadmap: {
      beginner: ["1. Blockchain fundamentals (Bitcoin whitepaper, consensus mechanisms)", "2. Ethereum & Smart Contract basics", "3. Learn Solidity (2 months)", "4. Build first smart contract on Remix IDE", "5. Deploy on Ethereum testnet", "6. Build a simple ERC-20 token"],
      intermediate: ["1. Advanced Solidity patterns", "2. DeFi protocol development (AMM, lending)", "3. NFT marketplace development", "4. Web3.js / Ethers.js for frontend integration", "5. Security: Common vulnerabilities (reentrancy, overflow)"],
      advanced: ["1. Smart contract security auditing", "2. Layer 2 development", "3. Cross-chain protocols", "4. Protocol design and tokenomics", "5. DAO governance systems"],
    },
    projects: ["🔹 ERC-20 Token + simple DEX", "🔹 NFT Minting dApp", "🔹 Decentralized Voting System", "🔹 DeFi Yield Aggregator (clone)"],
    jobRoles: ["Blockchain Developer", "Smart Contract Developer", "Solidity Engineer", "Web3 Frontend Developer", "DeFi Protocol Engineer", "Blockchain Security Auditor", "Crypto Quant Analyst"],
    salary: { india: "₹8 LPA (Fresher) → ₹30 LPA (Mid) → ₹80+ LPA (Senior/Auditor)", global: "$100K (Junior) → $180K (Mid) → $300K+ (Protocol Engineer)" },
    demand: "🟡 Medium-High. Highly cyclical — surges with crypto bull markets. Long-term adoption growing.",
    workPressure: "🟡 Medium — Remote-first, often async. But security pressure is high (a bug can cost millions).",
    aiRisk: { level: "🟢 Low", reason: "Blockchain is a niche requiring deep cryptography, protocol design, and security knowledge. AI cannot replicate this specialized expertise." },
    growth: "Junior Blockchain Dev → Blockchain Engineer → Senior Smart Contract Dev → Protocol Architect → CTO of Web3 Startup",
    certifications: ["Certified Blockchain Developer – Blockchain Council", "ConsenSys Blockchain Developer (free)", "Ethereum Foundation courses"],
    topCompanies: ["Polygon", "Chainlink", "OpenSea", "Coinbase", "Binance", "CoinDCX", "WazirX", "Mudrex"],
    freeResources: ["CryptoZombies (free Solidity tutorial)", "Ethereum.org learn portal", "Patrick Collins YouTube (free blockchain course ⭐)", "Buildspace (project-based learning)"],
    paidCourses: ["Alchemy University (partially free)", "Blockchain A-Z – Udemy", "Zero to Mastery Web3"],
    tools: ["Remix IDE", "Hardhat", "MetaMask", "Ethers.js", "OpenZeppelin", "Alchemy / Infura", "The Graph"],
    freelancing: "🟢 High-paying. Smart contract auditing and dApp development on Upwork/Gitcoin pay extremely well.",
    abroad: "🟢 Remote-first globally. Most Web3 projects are decentralized and hire worldwide.",
    indiaMarket: "Growing. Mumbai, Bengaluru. Still early stage — most high-paying roles are global remote.",
    dailyWork: "Write Solidity code, audit contracts, integrate frontend with blockchain, participate in protocol governance, review security reports.",
    interviewTips: ["Understand EVM deeply", "Know common smart contract vulnerabilities", "Be able to explain gas optimization", "Show audited or deployed contracts"],
    resumeTips: ["Link to deployed contracts on Etherscan", "Show GitHub with Solidity projects", "Mention any bug bounties or audits completed"],
    collegeDegree: "Not required. Skills and portfolio are what matter. Deep cryptography knowledge is valued.",
  },

  game_dev: {
    name: "Game Development",
    overview: "Game development involves designing and building video games for PC, console, mobile, and VR. It combines programming, art, design, and audio. A creative and technically demanding field.",
    skills: {
      technical: ["Unity (C#) or Unreal Engine (C++/Blueprints)", "Game physics & mathematics", "3D modeling basics (Blender)", "Shader programming", "Version control (Git)", "Mobile game optimization", "Multiplayer networking (Photon, Mirror)", "Game design principles"],
      soft: ["Creativity", "Passion for Games", "Storytelling", "Persistence", "Cross-discipline Collaboration"],
    },
    roadmap: {
      beginner: ["1. Learn C# basics (4 weeks)", "2. Unity fundamentals (2 months)", "3. Build 3 small games (Pong, Flappy Bird clone, Endless Runner)", "4. Learn 2D game development fully", "5. Publish on itch.io"],
      intermediate: ["1. 3D game development in Unity", "2. Game physics, AI, pathfinding (NavMesh)", "3. Mobile game optimization", "4. Monetization (ads, IAP)", "5. Publish on Play Store"],
      advanced: ["1. Unreal Engine 5", "2. Multiplayer game networking", "3. VR/AR development", "4. Shader and graphics programming", "5. Team lead game project"],
    },
    projects: ["🔹 2D Platformer Game (Unity)", "🔹 Mobile Endless Runner with ads", "🔹 Multiplayer card game (Photon)", "🔹 3D First-Person Exploration game"],
    jobRoles: ["Game Developer", "Unity Developer", "Unreal Engine Developer", "Game Designer", "Level Designer", "Game AI Programmer", "Technical Artist", "Game Producer"],
    salary: { india: "₹3.5 LPA (Fresher) → ₹14 LPA (Mid) → ₹35+ LPA (Senior/Lead)", global: "$60K (Junior) → $100K (Mid) → $150K+ (Senior)" },
    demand: "🟡 Medium. India's gaming market is growing rapidly. Mobile gaming is huge. AAA studio jobs are competitive globally.",
    workPressure: "🔴 High — 'Crunch culture' is real in gaming. Ship deadlines are intense, especially at AAA studios.",
    aiRisk: { level: "🟡 Medium", reason: "AI assists with NPC behavior, procedural content generation, and testing. Core game programming and design remain human-led but will evolve." },
    growth: "Junior Game Dev → Game Developer → Senior Game Developer → Lead Programmer → Game Director → Studio Head",
    certifications: ["Unity Certified Associate Game Developer", "Unreal Online Learning certificates (free)", "C# Programming certifications"],
    topCompanies: ["Zynga India", "Ubisoft India", "Nazara Games", "nCore Games", "Rockstar Games", "EA", "Epic Games"],
    freeResources: ["Unity Learn (official, free)", "Brackeys YouTube ⭐", "GDC talks (YouTube)", "itch.io community"],
    paidCourses: ["Complete C# Unity Game Developer – Udemy ⭐", "Unreal Engine 5 Bootcamp – Udemy"],
    tools: ["Unity", "Unreal Engine 5", "Blender", "Photon", "GitHub", "Wwise (audio)"],
    freelancing: "🟡 Moderate. Mobile game clones, Roblox game development, itch.io sales.",
    abroad: "🟡 Moderate. US (California), UK, Canada for AAA studios. Competition is very high globally.",
    indiaMarket: "Growing rapidly. Mobile gaming boom. Bengaluru has most game studios. Salaries catching up slowly.",
    dailyWork: "Code game mechanics, fix bugs, collaborate with artists and designers, playtesting, optimize performance.",
    interviewTips: ["Show portfolio of published games (itch.io, Play Store)", "Know Unity/Unreal API deeply", "Be ready for math questions (vectors, matrices)", "Show you can ship games — even small ones"],
    resumeTips: ["Link to playable games", "Show team-based projects (game jams)", "Mention specific engines and languages"],
    collegeDegree: "Not required. Published games are your portfolio. Game design degrees exist but are not mandatory.",
  },
};

module.exports = careerData;
